# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package 打包并发布

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: publish  # **指定使用 publish 环境，否则 secrets 读取不到**
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 设置jdk11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Import GPG Key
      run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

    - name: maven-settings-action 设置maven所需的账号密码
      uses: s4u/maven-settings-action@v3.1.0
      with:
        path: ${{ github.workspace }}/custom_settings.xml
        servers: |
          [
            {
              "id": "central",
              "username": "${{ secrets.USERNAME }}",
              "password": "${{ secrets.PASSWORD }}"
            }
          ]

    - name: Build with Maven 编译
      run: mvn -B package --file pom.xml
      
    - name: Publish to GitHub Packages Apache Maven 发布
      run: mvn deploy -s ${{ github.workspace }}/custom_settings.xml -Dgpg.passphrase="${{ secrets.MAVEN_GPG_PASSPHRASE }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
 
